version: "3"

services:
  app:
    image: devsamuel/microservice:1.0
    volumes:
      - ./:/var/www/html
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - 8020:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
